apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
        - name: nodejs-demo
          image: docker.io/ainakshi/nodejsdemo:latest # Docker image name
          ports:
            - containerPort: 3000
