apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-service
  namespace: default
spec:
  selector:
    app: nodejs-demo
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 3000 # Internal container port
  type: LoadBalancer
